'use client';

import { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { Check, FileDown, FileSignature, GripVertical, LockKeyhole, Mail, Save, ShieldCheck, UsersRound, X } from 'lucide-react';
import type { Tournament } from './data/tournaments';
import type { IntentSubmission } from '../db/intents';
import type { ChaperoneSubmission } from '../db/chaperones';
import type { Member } from '../db/members';
import type { JudgePool, StudentStatus, TournamentPlan } from '../db/tournament-plans';
import { resolveTournamentName } from './lib/tournament-matcher';

type StudentCard = { key:string; name:string; memberId:string|null; entries:IntentSubmission[]; judgeKeys:string[] };
type JudgeCard = { key:string; name:string; linkedStudentKeys:string[]; approved:'yes'|'no'|'unknown'; source:Set<'Intent form'|'Chaperone form'>; preferred:string|null };
type RosterEntity = { key:string; students:StudentCard[]; pfTeam:boolean; unmatchedPartnerLabel:string|null };
type EventFilter = 'all'|'pf'|'ld'|'speech'|'congress';
const poolLabels:Record<JudgePool,string>={available:'Available',debate:'Debate',speech:'Speech',congress:'Congress'};
const eventFilters:{value:EventFilter;label:string}[]=[{value:'all',label:'All'},{value:'pf',label:'PF'},{value:'ld',label:'LD'},{value:'speech',label:'Speech'},{value:'congress',label:'Congress'}];
function cleanKey(value:string){return value.trim().toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();}
function studentKey(intent:IntentSubmission){return intent.memberId??`intent:${cleanKey(intent.matchedStudentName??intent.studentNameRaw)}`;}
function judgeKey(name:string,email:string|null,phone:string|null){return `judge:${cleanKey(email||phone||name)}`;}
function entryMatchesFilter(entry:IntentSubmission,filter:EventFilter){return filter==='all'||entry.eventCategory===filter;}
function studentMatchesFilter(student:StudentCard,filter:EventFilter){return student.entries.some(entry=>entryMatchesFilter(entry,filter));}
function detailsMentionStudent(details:string|null,name:string){const detailKey=cleanKey(details??'');const nameKey=cleanKey(name);return nameKey.length>3&&` ${detailKey} `.includes(` ${nameKey} `);}
function judgeIdentityKeys(name:string,email:string|null,phone:string|null){
  const normalizedEmail=email?.trim().toLowerCase();
  const normalizedPhone=phone?.replace(/\D/g,'');
  return [
    normalizedEmail?`email:${normalizedEmail}`:null,
    normalizedPhone?`phone:${normalizedPhone}`:null,
    cleanKey(name)?`name:${cleanKey(name)}`:null,
  ].filter((value):value is string=>Boolean(value));
}
function isTournamentSubmission(submission:ChaperoneSubmission,tournament:Tournament,tournaments:Tournament[]){return submission.tournamentNames.some(name=>{const match=resolveTournamentName(name,tournaments);return match.status==='matched'&&match.tournament.id===tournament.id;});}

export function TournamentPlanner({ tournament, tournaments, intents, chaperones, members, initialPlan, onClose }:{tournament:Tournament;tournaments:Tournament[];intents:IntentSubmission[];chaperones:ChaperoneSubmission[];members:Member[];initialPlan:TournamentPlan|null;onClose:()=>void}){
  const router=useRouter();
  const relevantIntents=useMemo(()=>intents.filter(item=>item.tournamentId===tournament.id),[intents,tournament.id]);
  const students=useMemo(()=>{
    const grouped=new Map<string,StudentCard>();
    for(const intent of relevantIntents){const key=studentKey(intent);const card=grouped.get(key)??{key,name:intent.matchedStudentName??intent.studentNameRaw,memberId:intent.memberId,entries:[],judgeKeys:[]};card.entries.push(intent);grouped.set(key,card);}
    return Array.from(grouped.values()).sort((a,b)=>a.name.localeCompare(b.name));
  },[relevantIntents]);
  const membersById=useMemo(()=>new Map(members.map(member=>[member.id,member])),[members]);
  const judges=useMemo(()=>{
    const map=new Map<string,JudgeCard>();
    const identityIndex=new Map<string,string>();
    const add=(name:string,email:string|null,phone:string|null,linkedStudentKey:string|null,approved:JudgeCard['approved'],source:'Intent form'|'Chaperone form',preferred:string|null)=>{
      if(!name.trim())return;
      const identities=judgeIdentityKeys(name,email,phone);
      const key=identities.map(identity=>identityIndex.get(identity)).find((match):match is string=>Boolean(match))??judgeKey(name,email,phone);
      const item=map.get(key)??{key,name,linkedStudentKeys:[],approved,source:new Set(),preferred};
      if(linkedStudentKey&&!item.linkedStudentKeys.includes(linkedStudentKey))item.linkedStudentKeys.push(linkedStudentKey);if(approved==='yes'||item.approved==='unknown')item.approved=approved;item.source.add(source);if(!item.preferred&&preferred)item.preferred=preferred;map.set(key,item);
      identities.forEach(identity=>identityIndex.set(identity,key));
    };
    for(const intent of relevantIntents){const linked=studentKey(intent);if(intent.parent1Judging&&intent.parent1Name)add(intent.parent1Name,intent.parent1Email,intent.parent1Phone,linked,'unknown','Intent form',intent.eventCategory);if(intent.parent2Judging&&intent.parent2Name)add(intent.parent2Name,intent.parent2Email,intent.parent2Phone,linked,'unknown','Intent form',intent.eventCategory);}
    for(const submission of chaperones){if(!isTournamentSubmission(submission,tournament,tournaments))continue;const linked=submission.memberId?students.find(student=>student.memberId===submission.memberId)?.key??null:students.find(student=>cleanKey(student.name)===cleanKey(submission.matchedStudentName??submission.studentNameRaw))?.key??null;add(submission.parentName,submission.parentEmail,submission.parentPhone,linked,submission.approvedVolunteer,'Chaperone form',submission.desiredEvent);}
    return Array.from(map.values()).sort((a,b)=>a.name.localeCompare(b.name));
  },[chaperones,relevantIntents,students,tournament,tournaments]);

  const [judgeAssignments,setJudgeAssignments]=useState<Record<string,JudgePool>>({});
  const [studentStatuses,setStudentStatuses]=useState<Record<string,StudentStatus>>({});
  const [pfPartnerAssignments,setPfPartnerAssignments]=useState<Record<string,string>>({});
  const [intentFilter,setIntentFilter]=useState<EventFilter>('all');
  const [finalizedFilter,setFinalizedFilter]=useState<EventFilter>('all');
  const [confirmed,setConfirmed]=useState(false);
  const [saveState,setSaveState]=useState<'idle'|'saving'|'saved'|'error'>('idle');
  const [pdfState,setPdfState]=useState<'idle'|'creating'|'error'>('idle');
  useEffect(()=>{const assignments:Record<string,JudgePool>={};judges.forEach(judge=>assignments[judge.key]=initialPlan?.judgeAssignments[judge.key]??'available');const statuses:Record<string,StudentStatus>={};students.forEach(student=>statuses[student.key]=initialPlan?.studentStatuses[student.key]??'waitlist');setJudgeAssignments(assignments);setStudentStatuses(statuses);setPfPartnerAssignments(initialPlan?.pfPartnerAssignments??{});setIntentFilter('all');setFinalizedFilter('all');setConfirmed(initialPlan?.confirmed??false);setSaveState('idle');},[initialPlan,judges,students,tournament.id]);

  const autoPfPartnerKeys=useMemo(()=>{const pairs=new Map<string,string>();const pfStudents=students.filter(student=>student.entries.some(entry=>entry.eventCategory==='pf'));for(const student of pfStudents){const ownDetails=student.entries.filter(entry=>entry.eventCategory==='pf').map(entry=>entry.eventDetails);const matches=pfStudents.filter(candidate=>candidate.key!==student.key&&(ownDetails.some(details=>detailsMentionStudent(details,candidate.name))||candidate.entries.some(entry=>entry.eventCategory==='pf'&&detailsMentionStudent(entry.eventDetails,student.name))));if(matches.length===1&&!pairs.has(student.key)&&!pairs.has(matches[0].key)){pairs.set(student.key,matches[0].key);pairs.set(matches[0].key,student.key);}}return pairs;},[students]);
  const pfPartnerKeys=useMemo(()=>{const pairs=new Map(autoPfPartnerKeys);const pfKeys=new Set(students.filter(student=>student.entries.some(entry=>entry.eventCategory==='pf')).map(student=>student.key));for(const [key,partnerKey] of Object.entries(pfPartnerAssignments)){if(!pfKeys.has(key)||!pfKeys.has(partnerKey)||key===partnerKey)continue;const priorKey=pairs.get(key);const priorPartner=pairs.get(partnerKey);if(priorKey&&priorKey!==partnerKey)pairs.delete(priorKey);if(priorPartner&&priorPartner!==key)pairs.delete(priorPartner);pairs.set(key,partnerKey);pairs.set(partnerKey,key);}return pairs;},[autoPfPartnerKeys,pfPartnerAssignments,students]);
  const directlyLockedStudents=useMemo(()=>new Set(judges.filter(judge=>(judgeAssignments[judge.key]??'available')!=='available').flatMap(judge=>judge.linkedStudentKeys)),[judgeAssignments,judges]);
  const partnerLockedBy=useMemo(()=>{const result=new Map<string,string>();for(const key of directlyLockedStudents){const student=students.find(item=>item.key===key);if(!student?.entries.some(entry=>entry.eventCategory==='pf'))continue;const partnerKey=pfPartnerKeys.get(key);if(partnerKey)result.set(partnerKey,key);}return result;},[directlyLockedStudents,pfPartnerKeys,students]);
  const lockedStudents=useMemo(()=>new Set([...directlyLockedStudents,...partnerLockedBy.keys()]),[directlyLockedStudents,partnerLockedBy]);
  const rosterEntities=useMemo(()=>{const result:RosterEntity[]=[];const used=new Set<string>();for(const student of students){if(used.has(student.key))continue;const pfEntry=student.entries.find(entry=>entry.eventCategory==='pf');if(pfEntry){const partnerKey=pfPartnerKeys.get(student.key);const partner=partnerKey?students.find(item=>item.key===partnerKey):undefined;const teamStudents=partner?[student,partner].sort((a,b)=>a.name.localeCompare(b.name)):[student];teamStudents.forEach(item=>used.add(item.key));result.push({key:`pf:${teamStudents.map(item=>item.key).sort().join('+')}`,students:teamStudents,pfTeam:true,unmatchedPartnerLabel:partner?null:pfEntry.eventDetails});}else{used.add(student.key);result.push({key:`student:${student.key}`,students:[student],pfTeam:false,unmatchedPartnerLabel:null});}}return result.sort((a,b)=>a.students[0].name.localeCompare(b.students[0].name));},[pfPartnerKeys,students]);
  useEffect(()=>{setStudentStatuses(current=>{let changed=false;const next={...current};for(const key of lockedStudents){if(next[key]!=='going'){next[key]='going';changed=true;}}for(const entity of rosterEntities){if(!entity.pfTeam)continue;const teamGoing=entity.students.some(student=>next[student.key]==='going'||lockedStudents.has(student.key));if(teamGoing)for(const student of entity.students){if(next[student.key]!=='going'){next[student.key]='going';changed=true;}}}return changed?next:current;});},[lockedStudents,rosterEntities]);
  const goingStudents=students.filter(student=>(studentStatuses[student.key]??'waitlist')==='going'||lockedStudents.has(student.key));
  const waitlistStudents=students.filter(student=>!lockedStudents.has(student.key)&&(studentStatuses[student.key]??'waitlist')==='waitlist');
  const goingKeys=new Set(goingStudents.map(student=>student.key));
  const entityMatchesFilter=(entity:RosterEntity,filter:EventFilter)=>filter==='all'||(filter==='pf'?entity.pfTeam:entity.students.some(student=>studentMatchesFilter(student,filter)));
  const entityIsGoing=(entity:RosterEntity)=>entity.students.some(student=>goingKeys.has(student.key));
  const goingEntities=rosterEntities.filter(entityIsGoing);
  const waitlistEntities=rosterEntities.filter(entity=>!entityIsGoing(entity));
  const visibleGoingEntities=goingEntities.filter(entity=>entityMatchesFilter(entity,finalizedFilter));
  const visibleWaitlistEntities=waitlistEntities.filter(entity=>entityMatchesFilter(entity,intentFilter));
  const intentFilterCounts=Object.fromEntries(eventFilters.map(filter=>[filter.value,waitlistEntities.filter(entity=>entityMatchesFilter(entity,filter.value)).length])) as Record<EventFilter,number>;
  const finalizedFilterCounts=Object.fromEntries(eventFilters.map(filter=>[filter.value,goingEntities.filter(entity=>entityMatchesFilter(entity,filter.value)).length])) as Record<EventFilter,number>;
  const assignedJudges=(pool:JudgePool)=>judges.filter(judge=>(judgeAssignments[judge.key]??'available')===pool);
  const assignedCount=(pool:JudgePool)=>new Set(assignedJudges(pool).map(judge=>judge.key)).size;
  const sharedJudgeCount=(pool:JudgePool)=>assignedJudges(pool).filter(judge=>judge.linkedStudentKeys.length>1).length;
  const sharedJudgeNote=(pool:JudgePool)=>{const count=sharedJudgeCount(pool);return count?` · ${count} shared judge${count===1?'':'s'} counted once`:'';};
  const entries=relevantIntents.filter(intent=>goingKeys.has(studentKey(intent)));
  const ldEntries=entries.filter(item=>item.eventCategory==='ld').length;
  const pfStudents=entries.filter(item=>item.eventCategory==='pf').length;
  const debateUnits=ldEntries+Math.ceil(pfStudents/2);
  const speechEntries=entries.filter(item=>item.eventCategory==='speech').length;
  const congressEntries=entries.filter(item=>item.eventCategory==='congress').length;
  const capacity=[
    {label:'Debate',used:debateUnits,capacity:assignedCount('debate')*2,detail:`${ldEntries} LD + ${pfStudents} PF student${pfStudents===1?'':'s'}${sharedJudgeNote('debate')}`},
    {label:'Speech',used:speechEntries,capacity:assignedCount('speech')*5,detail:`5 entries per unique judge${sharedJudgeNote('speech')}`},
    {label:'Congress',used:congressEntries,capacity:assignedCount('congress')*5,detail:`5 entries per unique judge${sharedJudgeNote('congress')}`},
  ];
  const moveJudge=(key:string,pool:JudgePool)=>{setJudgeAssignments(value=>({...value,[key]:pool}));if(pool!=='available'){const judge=judges.find(item=>item.key===key);const forcedKeys=(judge?.linkedStudentKeys??[]).flatMap(studentKey=>[studentKey,pfPartnerKeys.get(studentKey)].filter((value):value is string=>Boolean(value)));if(forcedKeys.length)setStudentStatuses(value=>{const next={...value};forcedKeys.forEach(studentKey=>next[studentKey]='going');return next;});}setSaveState('idle');};
  const assignPfPartner=(key:string,partnerKey:string)=>{setPfPartnerAssignments(current=>{const next:Record<string,string>={};for(const [left,right] of Object.entries(current)){if(left!==key&&left!==partnerKey&&right!==key&&right!==partnerKey)next[left]=right;}if(partnerKey){next[key]=partnerKey;next[partnerKey]=key;}return next;});setSaveState('idle');};
  const clearPfPair=(keys:string[])=>{setPfPartnerAssignments(current=>Object.fromEntries(Object.entries(current).filter(([left,right])=>!keys.includes(left)&&!keys.includes(right))));setSaveState('idle');};
  const moveStudents=(keys:string[],status:StudentStatus)=>{if(status==='waitlist'&&keys.some(key=>lockedStudents.has(key)))return;setStudentStatuses(value=>{const next={...value};keys.forEach(key=>next[key]=status);return next;});setSaveState('idle');};
  const startDrag=(event:React.DragEvent,type:'judge'|'student',key:string,keys?:string[])=>{event.dataTransfer.effectAllowed='move';event.dataTransfer.setData('application/x-mrhs-card',JSON.stringify({type,key,keys}));};
  const drop=(event:React.DragEvent,target:JudgePool|StudentStatus)=>{event.preventDefault();try{const item=JSON.parse(event.dataTransfer.getData('application/x-mrhs-card')) as {type:string;key:string;keys?:string[]};if(item.type==='judge'&&['available','debate','speech','congress'].includes(target))moveJudge(item.key,target as JudgePool);if(item.type==='student'&&['going','waitlist'].includes(target))moveStudents(item.keys?.length?item.keys:[item.key],target as StudentStatus);}catch{/* Ignore unrelated drags. */}};
  const save=async(nextConfirmed=confirmed)=>{setSaveState('saving');try{const response=await fetch('/api/tournament-plan',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({tournamentId:tournament.id,judgeAssignments,studentStatuses,pfPartnerAssignments,confirmed:nextConfirmed})});if(!response.ok)throw new Error('Save failed');setConfirmed(nextConfirmed);setSaveState('saved');router.refresh();}catch{setSaveState('error');}};
  const finalizedEmails=Array.from(new Set(goingStudents.map(student=>{const member=student.memberId?membersById.get(student.memberId):null;return member?.schoolEmail??member?.personalEmail??member?.tabroomEmail??student.entries.find(entry=>entry.tabroomEmail)?.tabroomEmail??null;}).filter((value):value is string=>Boolean(value))));
  const gmailUrl=finalizedEmails.length?`https://mail.google.com/mail/?view=cm&fs=1&bcc=${encodeURIComponent(finalizedEmails.join(','))}&su=${encodeURIComponent(`${tournament.name} - finalized roster`)}&body=${encodeURIComponent(`Hi everyone,\n\nYou have been selected for the finalized roster for ${tournament.name} on ${tournament.dateLabel}. Please reply as soon as possible if you can no longer attend.\n\nCongratulations, and we will share the remaining tournament details shortly.`)}`:null;
  const downloadPdf=async()=>{setPdfState('creating');try{const rows=goingEntities.flatMap(entity=>entity.students.map(student=>{const partner=entity.pfTeam?entity.students.find(item=>item.key!==student.key)?.name??entity.unmatchedPartnerLabel??'Partner not matched':'';const event=Array.from(new Set(student.entries.map(entry=>entry.eventRaw))).join(', ');const coverage=directlyLockedStudents.has(student.key)?'Covered by linked judge':lockedStudents.has(student.key)?'Covered by partner judge':'Finalized selection';return{name:student.name,event,partner,coverage};}));const response=await fetch('/api/tournament-roster-pdf',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({tournamentName:tournament.name,dateLabel:tournament.dateLabel,location:tournament.location,rows})});if(!response.ok)throw new Error('PDF failed');const blob=await response.blob();const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`${tournament.id}-finalized-roster.pdf`;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url);setPdfState('idle');}catch{setPdfState('error');}};
  const renderJudge=(judge:JudgeCard)=>{const linkedNames=judge.linkedStudentKeys.map(key=>students.find(student=>student.key===key)?.name).filter(Boolean);const coverageLabel=linkedNames.length>1?`${linkedNames.length} linked students · one judge credit`:Array.from(judge.source).join(' + ');return <article className="judge-card" draggable onDragStart={event=>startDrag(event,'judge',judge.key)} key={judge.key}><GripVertical size={15}/><div><strong>{judge.name}</strong><small>{linkedNames.length?`Linked: ${linkedNames.join(', ')}`:'No student link'} · {coverageLabel}</small></div><span className={`approval-dot ${judge.approved}`}>{judge.approved==='yes'?'UCPS approved':judge.approved==='no'?'Approval needed':'Approval unknown'}</span><select aria-label={`Assign ${judge.name}`} value={judgeAssignments[judge.key]??'available'} onChange={event=>moveJudge(judge.key,event.target.value as JudgePool)}>{Object.entries(poolLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></article>;};
  const renderRosterEntity=(entity:RosterEntity,filter:EventFilter)=>{const keys=entity.students.map(student=>student.key);const locked=keys.some(key=>lockedStudents.has(key));const status=entityIsGoing(entity)?'going':'waitlist';const visibleEntries=entity.students.flatMap(student=>student.entries.filter(entry=>filter==='all'||entryMatchesFilter(entry,filter)).map(entry=>({student,entry})));const manualPair=entity.students.length===2&&keys.some(key=>Boolean(pfPartnerAssignments[key]));const partnerChoices=entity.pfTeam&&entity.students.length===1?students.filter(student=>student.key!==keys[0]&&student.entries.some(entry=>entry.eventCategory==='pf')&&!pfPartnerKeys.has(student.key)):[];return <article className={`student-card ${entity.pfTeam?'pf-team-card':''} ${locked?'locked':''}`} draggable={!locked} onDragStart={event=>startDrag(event,'student',entity.key,keys)} key={entity.key}><div className="student-card-top">{locked?<LockKeyhole size={15}/>:<GripVertical size={15}/>}<strong>{entity.pfTeam?'PF team':'Student entry'}</strong>{entity.pfTeam?<span className="team-badge">One unit</span>:null}</div><div className="team-members">{entity.students.map(student=>{const covered=directlyLockedStudents.has(student.key);return <div className={`team-member ${covered?'covered':''}`} key={student.key}><span>{covered?'Covered by judge':student.memberId&&membersById.get(student.memberId)?.membershipStatus==='Paid'?'Dues paid':'Student'}</span><strong>{student.name}</strong></div>;})}{entity.pfTeam&&entity.students.length===1?<label className="partner-picker"><span>Choose PF partner</span><select defaultValue="" onPointerDown={event=>event.stopPropagation()} onChange={event=>assignPfPartner(keys[0],event.target.value)}><option value="" disabled>{entity.unmatchedPartnerLabel??'Select the matching student'}</option>{partnerChoices.map(student=><option value={student.key} key={student.key}>{student.name}</option>)}</select></label>:null}{manualPair&&!locked?<button className="team-unpair" type="button" onClick={()=>clearPfPair(keys)}>Change partner pairing</button>:null}</div><div className="student-events">{visibleEntries.map(({student,entry})=><span key={entry.id}>{entity.students.length>1?`${student.name.split(' ')[0]} · `:''}{entry.eventRaw}{entry.eventDetails?` · ${entry.eventDetails}`:''}</span>)}</div><footer>{locked?<b>{entity.pfTeam?'PF team locked by judge':'Locked by linked judge'}</b>:<button type="button" onClick={()=>moveStudents(keys,status==='going'?'waitlist':'going')}>{status==='going'?'Return to intent pool':'Add to finalized roster'}</button>}</footer></article>;};

  return <div className="planner-backdrop" role="dialog" aria-modal="true" aria-label={`${tournament.name} staffing planner`}>
    <section className="planner-shell">
      <header className="planner-header"><div><p className="eyebrow">Tournament operations board</p><h2>{tournament.name}</h2><span>{tournament.dateLabel} · {tournament.location}</span></div><div className="planner-actions"><span className={`save-state ${saveState}`}>{saveState==='saving'?'Saving…':saveState==='saved'?'Saved':saveState==='error'?'Save failed':''}</span><a className="outline-button roster-action" href={`/api/tournament-permission-form?tournamentId=${encodeURIComponent(tournament.id)}`}><FileSignature size={15}/>Permission form</a><button className="outline-button" onClick={()=>void save()} type="button"><Save size={15}/>Save draft</button><button className={`confirm-button ${confirmed?'confirmed':''}`} onClick={()=>void save(!confirmed)} type="button"><Check size={16}/>{confirmed?'Roster confirmed':'Confirm roster'}</button>{confirmed?<><button className="outline-button roster-action" onClick={()=>void downloadPdf()} type="button"><FileDown size={15}/>{pdfState==='creating'?'Creating PDF…':pdfState==='error'?'Try PDF again':'Download PDF'}</button><a className={`outline-button roster-action ${gmailUrl?'':'disabled'}`} href={gmailUrl??undefined} target="_blank" rel="noreferrer" aria-disabled={!gmailUrl} title={gmailUrl?'Open Gmail with the finalized roster in BCC':'No student email addresses are available'}><Mail size={15}/>Email roster</a></>:null}<button className="planner-close" onClick={onClose} aria-label="Close planner" type="button"><X size={21}/></button></div></header>
      <section className="capacity-ribbon">{capacity.map(item=><article className={item.used>item.capacity?'over':''} key={item.label}><span>{item.label}</span><strong>{item.used} / {item.capacity}</strong><small>{item.used>item.capacity?`${item.used-item.capacity} over capacity`:item.detail}</small></article>)}<article><span>Finalized roster</span><strong>{goingStudents.length}</strong><small>{waitlistStudents.length} in intent pool · {lockedStudents.size} locked</small></article></section>
      {!relevantIntents.length?<div className="planner-empty"><UsersRound size={30}/><h3>No intent submissions matched yet.</h3><p>Once a student submits the tournament intent form, their card will appear here automatically.</p></div>:<>
        <section className="judge-board"><div className="board-title"><div><p className="eyebrow">Adult coverage</p><h3>Drag judges between pools</h3></div><p>Assigning a parent locks every linked student into the roster. A parent linked to two students still provides only one judge credit.</p></div><div className="judge-columns">{(['available','debate','speech','congress'] as JudgePool[]).map(pool=><section className="drop-column" key={pool} onDragOver={event=>event.preventDefault()} onDrop={event=>drop(event,pool)}><header><span>{poolLabels[pool]}</span><b>{assignedCount(pool)}</b></header><div>{assignedJudges(pool).map(renderJudge)}{!assignedJudges(pool).length?<p className="drop-hint">Drop judge here</p>:null}</div></section>)}</div></section>
        <section className="student-board"><div className="board-title"><div><p className="eyebrow">Intent roster</p><h3>Build the finalized roster</h3></div><p>PF partners stay in one card and move together. The student providing the linked judge is highlighted in green.</p></div><div className="student-columns"><section className="student-drop intent-pool" onDragOver={event=>event.preventDefault()} onDrop={event=>drop(event,'waitlist')}><header><span>Intent pool</span><b>{visibleWaitlistEntities.length}</b></header><div className="event-filter-bar" role="group" aria-label="Filter the intent pool by event">{eventFilters.map(filter=><button type="button" className={intentFilter===filter.value?'active':''} aria-pressed={intentFilter===filter.value} onClick={()=>setIntentFilter(filter.value)} key={filter.value}><span>{filter.label}</span><b>{intentFilterCounts[filter.value]}</b></button>)}</div><div className="student-card-grid">{visibleWaitlistEntities.map(entity=>renderRosterEntity(entity,intentFilter))}{!visibleWaitlistEntities.length?<p className="drop-hint">No entries in the intent pool match this event.</p>:null}</div></section><section className="student-drop finalized-roster" onDragOver={event=>event.preventDefault()} onDrop={event=>drop(event,'going')}><header><span>Finalized roster</span><b>{visibleGoingEntities.length}</b></header><div className="event-filter-bar" role="group" aria-label="Filter the finalized roster by event">{eventFilters.map(filter=><button type="button" className={finalizedFilter===filter.value?'active':''} aria-pressed={finalizedFilter===filter.value} onClick={()=>setFinalizedFilter(filter.value)} key={filter.value}><span>{filter.label}</span><b>{finalizedFilterCounts[filter.value]}</b></button>)}</div><div className="student-card-grid">{visibleGoingEntities.map(entity=>renderRosterEntity(entity,finalizedFilter))}{!visibleGoingEntities.length?<p className="drop-hint">No finalized entries match this event.</p>:null}</div></section></div></section>
      </>}
      <footer className="planner-footnote"><ShieldCheck size={16}/><span>Shared management plan · saved to the private dashboard database. Parent contact details and student submissions never appear on the public login screen.</span></footer>
    </section>
  </div>;
}
